### ISSUE TITLE
Blender crashes when using script in certain circumstances.

### ISSUE THREAD

**Issue by ThomasLynn** [JMY1000/CyclesMineways#11]
When I was making USER_INPUT_SCENE respect scenes, I was on blender render (not cycles) on another scene (that the script shouldn't have touched), with another cycles scene with a mineways .obj in. After I ran the script, Blender would crash if I used the rendered view port in the blender render scene (instant shutdown, not a freeze).

I have a feeling it's either due to the script still accessing things it shouldn't, or an internal Blender problem.

How to recreate the problem:
download this .blend https://www.mediafire.com/?347evt90fsnfskl
be on Scene.001
load in script and change USER_INPUT_SCENE from [] to ["Scene"]
run the script
change the view port to rendered mode

**Comment by JMY1000** [comment]
Please pack all the relevant resources (including texture files) into the .blend, otherwise the shaders don't work.

**Comment by ThomasLynn** [comment]
I packed the .blend and updated the file in the link, try now.

**Comment by JMY1000** [comment]
Could not reproduce. Try looking at the console and see what it says when you run it to see if there's anything out of the ordinary.

**Comment by ThomasLynn** [comment]
I tested again running it through the CMD window, the error log was

Texture test-RGBA.png.017 removed for being a duplicate.
Texture test-RGBA.png.018 removed for being a duplicate.
Texture test-RGBA.png.019 removed for being a duplicate.
Finished removing unnecessary textures

Cycles Mineways has finished.

Error: EXCEPTION_ACCESS_VIOLATION

then closes. Did you definitely set USER_INPUT_SCENE from [] to ["Scene"]? If you did, then it's probably something to do with my graphics card + blender

**Comment by JMY1000** [comment]
Yes I did. I didn't have that error at the end. Try using CPU render for the viewport and see if that works.

**Comment by ThomasLynn** [comment]
Blender internal engine doesn't have GPU/CPU render options.

**Comment by JMY1000** [comment]
My bad. Still don't know what's happening then.
