### ISSUE TITLE
Solid block (type 0) water shader doesn't work

### ISSUE THREAD

**Issue by JMY1000** [JMY1000/CyclesMineways#13]
Probably an easy fix, I'll look into it

**Comment by ThomasLynn** [comment]
There was a little error in my math (less than) node. I've fixed it.

**Comment by erich666** [comment]
Just to make things exciting, I'm modifying how the water material's texture is created in Mineways, making it more consistent with the rest of the system. This is just a heads up; version 5.01 (out this weekend, if all goes well) will have this change in it.
