### ISSUE TITLE
Minecraft 1.9 Support

### ISSUE THREAD

**Issue by JMY1000** [JMY1000/CyclesMineways#5]
Minecraft 1.9 was released yesterday. Although [Mineways](https://github.com/erich666/Mineways) doesn't yet support it, preparations need to be made for it.

**Comment by erich666** [comment]
Mineways probably will support it in a week. I worked on the main hunks of code on Monday, now I need a bunch of hours to finish up.

**Comment by JMY1000** [comment]
Support has been added with v1.2.1
