### ISSUE TITLE
Emission Shader and Transparent Emission Shader are Different

### ISSUE THREAD

**Issue by JMY1000** [JMY1000/CyclesMineways#9]
Title. Leftover from shader change of the emission shader.

**Comment by JMY1000** [comment]
A copy of the shader from the emission shader to the transparent emission shader won't work due to massive amounts of noise. Though this can be solved with added geometry, we want to refrain from that.

**Comment by ThomasLynn** [comment]
In the mean time, we could give the option to use the light block's node setup as an option. If we keep it the way it is, torches and such won't emit a proper amount of light, if we use the light block's setup, we will get loads of noise, if we add geometry, it needs to be done right, or torches will be completely broken.

**Comment by ThomasLynn** [comment]
This should be fixed in the update I just made.
